Repository nmdickson/GCfit, pull requests merged in 2022-11, with the labels that each got.

#159 add units to the `_get_labels` of individual runs
  fitter/analysis/runs.py
Labels: plotting

#160 fix labels positioning in `plot_mass_func`
  fitter/analysis/models.py
Labels: bug, plotting

#161 fix small bug in saving `GCFIT_DIR` to metadata
  fitter/core/main.py
Labels: bug

#153 Rewrite `cluster_component` (fixes #16).
  fitter/probabilities/probabilities.py
  fitter/probabilities/pulsars.py
  fitter/util/probabilities.py
Labels: bug
